# Author: Juergen Krawitz
# Email: Juergen.Krawitz@SMA.de
# Copyright: Copyright 2025, SMA Solar Technology AG
# License: MIT

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      # Run the formatter.
      - id: ruff-format
        name: "ğŸ python: Format with Ruff"
      # Run the linter.
      - id: ruff
        name: "ğŸ python: Lint with Ruff"
        args: [ --fix ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-docstring-first
        name: "ğŸ python: No code before docstrings"
      - id: debug-statements
        name: "ğŸ python: No debugger imports or breakpoint-calls"
      - id: detect-private-key
        name: "ğŸ”’ security: No private keys"
      - id: check-ast
        name: "ğŸ“ filesystem/content: .py-files are valid"
      - id: check-toml
        name: "ğŸ“ filesystem/content: .toml-files are valid"
      - id: check-yaml
        name: "ğŸ“ filesystem/content: .yaml-files are valid"
      - id: end-of-file-fixer
        name: "ğŸ“ filesystem/content: Files end in a newline"
      - id: trailing-whitespace
        name: "ğŸ“ filesystem/content: Trims trailing whitespace"
      - id: check-case-conflict
        name: "ğŸ“ filesystem/names: Check case sensitivity"
      - id: check-illegal-windows-names
        name: "ğŸ“ filesystem/names: Check Windows filenames"
      - id: name-tests-test
        name: "ğŸ“ filesystem/names: Check test file names"
      - id: check-symlinks
        name: "ğŸ“ filesystem/symlinks: Validate symlinks"
      - id: destroyed-symlinks
        name: "ğŸ“ filesystem/symlinks: No broken symlinks"
      - id: check-added-large-files
        name: "ğŸŒ³ git: No giant files"
      - id: forbid-submodules
        name: "ğŸŒ³ git: No git submodules"
      - id: no-commit-to-branch
        name: "ğŸŒ³ git: Protect the develop branch"
        args: [ --branch, develop ]
      - id: check-merge-conflict
        name: "ğŸŒ³ git: No unresolved merge conflict strings"
